apiVersion: v1
kind: ConfigMap
metadata:
  name: photonic-mlir-config
  namespace: photonic-mlir
  labels:
    app: photonic-mlir
data:
  production.yaml: |
    server:
      host: "0.0.0.0"
      port: 8080
      workers: 4
      max_requests: 1000
      timeout: 300

    cache:
      enabled: true
      backend: "redis"
      size_mb: 1024
      ttl_seconds: 3600

    logging:
      level: "INFO"
      format: "json"
      file: "/logs/photonic-mlir.log"
      max_size: "100MB"
      backup_count: 5

    security:
      enable_auth: true
      cors_origins:
        - "*"
      rate_limiting:
        enabled: true
        requests_per_minute: 60
        burst_size: 10

    hardware:
      enable_gpu: false
      max_concurrent_jobs: 10
      timeout_seconds: 300

    monitoring:
      enable_metrics: true
      metrics_port: 9090
      health_check_interval: 30

    compilation:
      max_model_size_mb: 100
      max_wavelengths: 32
      max_power_budget_mw: 1000
      cache_enabled: true

  logging.json: |
    {
      "version": 1,
      "disable_existing_loggers": false,
      "formatters": {
        "json": {
          "format": "%(asctime)s %(name)s %(levelname)s %(message)s",
          "class": "pythonjsonlogger.jsonlogger.JsonFormatter"
        },
        "simple": {
          "format": "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
        }
      },
      "handlers": {
        "file": {
          "class": "logging.handlers.RotatingFileHandler",
          "filename": "/logs/photonic-mlir.log",
          "maxBytes": 104857600,
          "backupCount": 10,
          "formatter": "json"
        },
        "stdout": {
          "class": "logging.StreamHandler",
          "stream": "ext://sys.stdout",
          "formatter": "json"
        }
      },
      "loggers": {
        "photonic_mlir": {
          "level": "INFO",
          "handlers": ["file", "stdout"],
          "propagate": false
        },
        "uvicorn": {
          "level": "INFO",
          "handlers": ["stdout"],
          "propagate": false
        }
      },
      "root": {
        "level": "INFO",
        "handlers": ["stdout"]
      }
    }