apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: photonic-mlir-data
  namespace: photonic-mlir
  labels:
    app: photonic-mlir
    type: data
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  storageClassName: fast-ssd

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: photonic-mlir-logs
  namespace: photonic-mlir
  labels:
    app: photonic-mlir
    type: logs
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: standard